/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <BitMath.h>
#include <std_typo.h>
#include <rcc_int.h>
#include <GPIO_interface.h>
#include "NVIC.h"
#include "SYSTICK.h"
#include "delay.h"
#include "keypad.h"
#include "7_segmant.h"
#include "app.h"
#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


u8 digits[4] = {0, 0, 0, 0};

void toggle_led(u8 val);
extern u8 flag;

int main(void)
{
	/* Loop forever */
	MRCC_voidInit();
	MRCC_enumSetPeripheralClock(APB2, GPIOA , RCC_ENABLE );
	MRCC_enumSetPeripheralClock(APB2, GPIOB , RCC_ENABLE );
	SYSTICK_Init();
	SYSTICK_SetCallback(toggle_led);
	SYSTICK_SetTime(1, HSI_CLOCK);
	Keypad_init();
	Init_Segmant();
	Init_leds();


	while(1){

		if(flag == 1){
			inc_watch();
			flag = 0;
		}
		uint8 val = 'x';
		val = Keypad_get_pressed_key();
		stop_watch(val);

		for(u8 i = 0; i < 4; i++){
			Segmant_Display(digits[i]);
			select(i);
		}

	}
}


void toggle_led(u8 val){
	DIO_voidSetPinDirection(PORTA, PIN11, GPIO_OUTPUT_10MHZ_PP);
	DIO_voidSetPinValue(PORTA, PIN11, val);
}
